from datetime import date, datetime, timedelta

from .schemas import Device, DeviceStatus, MaintenancePlan, ProductionTask, TaskStatus

NOW = datetime(2026, 4, 25, 16, 0, 0)

DEVICES: list[Device] = [
    Device(
        id="EQ-AC-001",
        name="空调外机装配线 A",
        workshop="总装一车间",
        status=DeviceStatus.running,
        health_index=86,
        rul_hours=186,
        air_temperature=298.4,
        process_temperature=309.1,
        rotational_speed=1480,
        torque=38.2,
        tool_wear=94,
        load_rate=0.78,
        updated_at=NOW,
    ),
    Device(
        id="EQ-AC-002",
        name="压缩机测试台 B",
        workshop="检测车间",
        status=DeviceStatus.warning,
        health_index=42,
        rul_hours=38,
        air_temperature=302.8,
        process_temperature=314.6,
        rotational_speed=1710,
        torque=49.8,
        tool_wear=174,
        load_rate=0.46,
        updated_at=NOW,
    ),
    Device(
        id="EQ-AC-003",
        name="蒸发器焊接工位 C",
        workshop="钣金车间",
        status=DeviceStatus.running,
        health_index=73,
        rul_hours=112,
        air_temperature=300.1,
        process_temperature=310.4,
        rotational_speed=1365,
        torque=34.6,
        tool_wear=121,
        load_rate=0.64,
        updated_at=NOW,
    ),
    Device(
        id="EQ-AC-004",
        name="包装输送线 D",
        workshop="包装车间",
        status=DeviceStatus.maintenance,
        health_index=29,
        rul_hours=12,
        air_temperature=304.2,
        process_temperature=318.3,
        rotational_speed=1890,
        torque=55.3,
        tool_wear=215,
        load_rate=0.18,
        updated_at=NOW,
    ),
]

MAINTENANCE_PLANS: list[MaintenancePlan] = [
    MaintenancePlan(
        id="MP-20260425-001",
        device_id="EQ-AC-004",
        device_name="包装输送线 D",
        window_start=NOW + timedelta(hours=2),
        window_end=NOW + timedelta(hours=5),
        reason="HI 低于 30，进入高风险维护窗口",
        priority="high",
        status="scheduled",
    ),
    MaintenancePlan(
        id="MP-20260425-002",
        device_id="EQ-AC-002",
        device_name="压缩机测试台 B",
        window_start=NOW + timedelta(days=1, hours=1),
        window_end=NOW + timedelta(days=1, hours=3),
        reason="RUL 小于 48 小时，建议安排预防性维护",
        priority="medium",
        status="pending",
    ),
]

PRODUCTION_TASKS: list[ProductionTask] = [
    ProductionTask(
        id="PT-001",
        order_no="MO-20260425-1001",
        product_name="1.5P 变频空调外机",
        planned_quantity=260,
        load_level="heavy",
        due_date=date(2026, 4, 27),
        assigned_device_id="EQ-AC-001",
        assigned_device_name="空调外机装配线 A",
        status=TaskStatus.running,
    ),
    ProductionTask(
        id="PT-002",
        order_no="MO-20260425-1002",
        product_name="压缩机性能测试批次",
        planned_quantity=120,
        load_level="medium",
        due_date=date(2026, 4, 26),
        assigned_device_id="EQ-AC-003",
        assigned_device_name="蒸发器焊接工位 C",
        status=TaskStatus.running,
    ),
    ProductionTask(
        id="PT-003",
        order_no="MO-20260425-1003",
        product_name="包装复检任务",
        planned_quantity=180,
        load_level="light",
        due_date=date(2026, 4, 28),
        assigned_device_id="EQ-AC-002",
        assigned_device_name="压缩机测试台 B",
        status=TaskStatus.pending,
    ),
]

